import {
  avatar1,
  avatar10,
  avatar2,
  avatar3,
  avatar4,
  avatar5,
  pledge1,
  pledge2,
  pledge3,
  pledge4,
  pledge5,
  pledge6,
} from "../assets/images";

export const pledge = [
  {
    id: "22",
    title: "BoredApe",
    desc: "A Bored Ape exuding regal elegance and confidence. This NFT represents the embodiment of strength and leadership.",
    imgUrl: pledge1,
    creator: "1000",
    creatorImg: avatar1,
    currentBid: "4999",
    percent: 2.4,
    days: 2,
    people: 43100,
    min: 1000,
    max: 4999,
  },

  {
    id: "23",
    title: "BoredApe",
    desc: "A Bored Ape with a stoic expression, hinting at the wisdom and depth within. Dive into the profound world of this NFT and uncover its hidden stories.",
    imgUrl: pledge2,
    creator: "5000",
    creatorImg: avatar2,
    currentBid: "9999",
    percent: 3,
    days: 4,
    people: 41700,
    min: 5000,
    max: 9999,
  },

  {
    id: "24",
    title: "BoredApe",
    desc: "A Bored Ape with a mischievous grin, ready to unleash its playful spirit upon the world. This NFT captures the essence of curiosity and adventure",
    imgUrl: pledge3,
    creator: "10000",
    creatorImg: avatar3,
    currentBid: "49999",
    percent: 3.5,
    days: 7,
    people: 44800,
    min: 10000,
    max: 49999,
  },

  {
    id: "25",
    title: "BoredApe",
    desc: "An enchanting Bored Ape adorned with vibrant accessories, radiating a contagious energy that draws you into its captivating gaze",
    imgUrl: pledge4,
    creator: "50000",
    creatorImg: avatar4,
    currentBid: "99999",
    percent: 4,
    days: 14,
    people: 47100,
    min: 50000,
    max: 99999,
  },

  {
    id: "26",
    title: "BoredApe",
    desc: "An artistic masterpiece featuring a Bored Ape surrounded by mesmerizing patterns and intricate details. It's a visual feast for the eyes and a testament to artistic creativity.",
    imgUrl: pledge5,
    creator: "100000",
    creatorImg: avatar5,
    currentBid: "199999",
    percent: 4.5,
    days: 21,
    people: 46300,
    min: 100000,
    max: 199999,
  },

  {
    id: "27",
    title: "BoredApe",
    desc: "A Bored Ape depicted in a dreamlike landscape, symbolizing the power of imagination and the escape from everyday monotony. Let this NFT transport you to a world of fantasy and wonder.",
    imgUrl: pledge6,
    creator: "200000",
    creatorImg: avatar10,
    currentBid: "500000",
    percent: 5,
    days: 30,
    people: 43900,
    min: 200000,
    max: 500000,
  },
];
