import {
  avatar1,
  avatar2,
  avatar3,
  avatar4,
  avatar5,
  avatar6,
  stake1,
  stake2,
  stake3,
  stake4,
  stake5,
  stake6,
} from "../assets/images";

export const stake = [
  {
    id: "01",
    title: "Ethereal Symphony",
    desc: "A mesmerizing fusion of colors and shapes, capturing the essence of imagination. Let the ethereal symphony of this artwork transport you to otherworldly realms.",
    imgUrl: stake1,
    creator: "100",
    creatorImg: avatar1,
    currentBid: "4999",
    percent: 1.5,
    min: 100,
    max: 4999,
  },

  {
    id: "02",
    title: "Transcendent Horizon",
    desc: "Embark on a journey through transcendent horizons where reality intertwines with the surreal. Explore the depths of this digital masterpiece and discover hidden dimensions.",
    imgUrl: stake2,
    creator: "5000",
    creatorImg: avatar2,
    currentBid: "19999",
    percent: 2,
    min: 5000,
    max: 19999,
  },

  {
    id: "03",
    title: "Whimsical Dreamscape",
    desc: "Step into a whimsical dreamscape, where vibrant hues dance with imaginative forms. Lose yourself in this captivating artwork and let your dreams take flight.",
    imgUrl: stake3,
    creator: "20000",
    creatorImg: avatar3,
    currentBid: "49999",
    percent: 3,
    min: 20000,
    max: 49999,
  },

  {
    id: "04",
    title: "Mystic Illumination",
    desc: "Experience the mystic illumination emanating from this enchanting artwork. Delve into its intricate patterns and let the ethereal glow guide you to newfound inspiration.",
    imgUrl: stake4,
    creator: "50000",
    creatorImg: avatar4,
    currentBid: "99999",
    percent: 3.3,
    min: 50000,
    max: 99999,
  },

  {
    id: "05",
    title: "Celestial Fusion",
    desc: "Witness the celestial fusion of cosmic energy and earthly elements in this awe-inspiring artwork. Allow its harmonious composition to elevate your spirit.",
    imgUrl: stake5,
    creator: "100000",
    creatorImg: avatar5,
    currentBid: "199999",
    percent: 3.7,
    min: 100000,
    max: 199999,
  },

  {
    id: "06",
    title: "Abstract Rhapsody",
    desc: "Prepare for epic collisions of imagination and creativity. This artwork brings together diverse elements in a harmonious symphony, igniting sparks of inspiration.",
    imgUrl: stake6,
    creator: "200000",
    creatorImg: avatar6,
    currentBid: "1000000",
    percent: 4.2,
    min: 200000,
    max: 1000000,
  },
];
